language: php 

php:
    - 5.4
    - 5.5
    - 5.6
   
env:
    - REPORT_EXIT_STATUS=1 NO_INTERACTION=1
    - CFLAGS=-std=c99

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script:
    - ./travis/run-test.sh
